version: "3"
services:
  db:
    image: cassandra
    ports:
      - "9042:9042"
    restart: always
  web:
    depends_on:
      - db
    links:
      - "db"
      - "db:database"
    # replace username/repo:tag with your name and image details
    image: webapp
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8000:80"
    networks:
      - webnet
networks:
  webnet: